os: linux
dist: trusty

language: php

if: tag IS blank

services:
  - mysql

env:
  global:
    - DB_BITRIX_HOST=localhost
    - DB_BITRIX_LOGIN=root
    - DB_BITRIX_PASS=root
    - DB_BITRIX_NAME=bitrix
    - BITRIX_PATH=$TRAVIS_BUILD_DIR/bitrix

stages:
  - test

install:
  - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'mbstring.func_overload = 2' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'mbstring.internal_encoding = "UTF-8"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - make create_db
  - make bitrix_install
  - composer install

script: make test

jobs:
  include:
    - php: 7.0
      env: USE_VENDOR=1
    - php: 7.1
    - php: 7.2
    - php: 7.3
